In [1]:
import torch

### Example

In [30]:
pid_A = 0
pid_B = 1

BLOCK_SIZE_A = 4
BLOCK_SIZE_B = 6
BLOCK_SIZE_D = 2

In [33]:
B = 12
A = 8
D = 4

In [36]:
tensor_a = torch.rand(A, D)
tensor_b = torch.rand(D, B)
tensor_c = torch.empty((A, B))

In [37]:
tensor_a, tensor_b, tensor_c

(tensor([[0.1373, 0.7348, 0.4368, 0.5475],
         [0.8483, 0.1495, 0.0260, 0.6770],
         [0.2306, 0.4092, 0.9679, 0.7157],
         [0.5682, 0.4072, 0.8114, 0.1402],
         [0.7619, 0.2217, 0.2537, 0.1926],
         [0.4510, 0.1049, 0.2820, 0.9318],
         [0.6456, 0.8339, 0.3056, 0.5064],
         [0.0432, 0.9534, 0.0015, 0.0988]]),
 tensor([[0.7508, 0.6766, 0.3780, 0.5883, 0.5127, 0.2102, 0.3844, 0.0625, 0.7391,
          0.2624, 0.0713, 0.4755],
         [0.3398, 0.6220, 0.3097, 0.9338, 0.4334, 0.6573, 0.1698, 0.1777, 0.8217,
          0.7828, 0.9970, 0.6746],
         [0.0518, 0.7745, 0.6985, 0.2000, 0.2051, 0.2398, 0.6945, 0.9568, 0.1969,
          0.3315, 0.9353, 0.6073],
         [0.8250, 0.6915, 0.5485, 0.5870, 0.0683, 0.7842, 0.4909, 0.6290, 0.9622,
          0.9800, 0.3739, 0.8674]]),
 tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       

In [38]:
tensor_a.shape, tensor_b.shape

(torch.Size([8, 4]), torch.Size([4, 12]))

In [34]:
(A, D), (D, B)

((8, 4), (4, 12))

In [45]:
stride_a_A = tensor_a.stride(0)
stride_a_D = tensor_a.stride(1)

stride_b_D = tensor_b.stride(0)
stride_b_B = tensor_b.stride(1)

stride_c_A = tensor_c.stride(0)
stride_c_B = tensor_c.stride(1)

In [46]:
stride_a_A, stride_a_D

(4, 1)

In [47]:
stride_b_D, stride_b_B

(12, 1)

In [48]:
stride_c_A, stride_c_B

(12, 1)

In [49]:
offsets_A = pid_A * BLOCK_SIZE_A + torch.arange(0, BLOCK_SIZE_A)
offsets_B = pid_B * BLOCK_SIZE_B + torch.arange(0, BLOCK_SIZE_B)
offsets_D = torch.arange(0, BLOCK_SIZE_D)

In [50]:
offsets_A, offsets_B, offsets_D

(tensor([0, 1, 2, 3]), tensor([ 6,  7,  8,  9, 10, 11]), tensor([0, 1]))

In [51]:
offsets_a = offsets_A[:, None] * stride_a_A + offsets_D[None, :] * stride_a_D
offsets_b = offsets_D[:, None] * stride_b_D + offsets_B[None, :] * stride_b_B

In [55]:
offsets_A

tensor([0, 1, 2, 3])

In [57]:
offsets_A[:, None] * stride_a_A

tensor([[ 0],
        [ 4],
        [ 8],
        [12]])

In [52]:
offsets_a.shape, offsets_b.shape

(torch.Size([4, 2]), torch.Size([2, 6]))

In [54]:
offsets_a, offsets_b

(tensor([[ 0,  1],
         [ 4,  5],
         [ 8,  9],
         [12, 13]]),
 tensor([[ 6,  7,  8,  9, 10, 11],
         [18, 19, 20, 21, 22, 23]]))